<?php

/**
 * A utility class that provides commonly used functionality.
 */
class MidiUtility {

  /** returns list of standard instrument names */
  public static function getInstrumentList() {
    return array(
      'Piano',
      'Bright Piano',
      'Electric Grand',
      'Honky Tonk Piano',
      'Electric Piano 1',
      'Electric Piano 2',
      'Harpsichord',
      'Clavinet',
      'Celesta',
      'Glockenspiel',
      'Music Box',
      'Vibraphone',
      'Marimba',
      'Xylophone',
      'Tubular Bell',
      'Dulcimer',
      'Hammond Organ',
      'Perc Organ',
      'Rock Organ',
      'Church Organ',
      'Reed Organ',
      'Accordion',
      'Harmonica',
      'Tango Accordion',
      'Nylon Str Guitar',
      'Steel String Guitar',
      'Jazz Electric Gtr',
      'Clean Guitar',
      'Muted Guitar',
      'Overdrive Guitar',
      'Distortion Guitar',
      'Guitar Harmonics',
      'Acoustic Bass',
      'Fingered Bass',
      'Picked Bass',
      'Fretless Bass',
      'Slap Bass 1',
      'Slap Bass 2',
      'Syn Bass 1',
      'Syn Bass 2',
      'Violin',
      'Viola',
      'Cello',
      'Contrabass',
      'Tremolo Strings',
      'Pizzicato Strings',
      'Orchestral Harp',
      'Timpani',
      'Ensemble Strings',
      'Slow Strings',
      'Synth Strings 1',
      'Synth Strings 2',
      'Choir Aahs',
      'Voice Oohs',
      'Syn Choir',
      'Orchestra Hit',
      'Trumpet',
      'Trombone',
      'Tuba',
      'Muted Trumpet',
      'French Horn',
      'Brass Ensemble',
      'Syn Brass 1',
      'Syn Brass 2',
      'Soprano Sax',
      'Alto Sax',
      'Tenor Sax',
      'Baritone Sax',
      'Oboe',
      'English Horn',
      'Bassoon',
      'Clarinet',
      'Piccolo',
      'Flute',
      'Recorder',
      'Pan Flute',
      'Bottle Blow',
      'Shakuhachi',
      'Whistle',
      'Ocarina',
      'Syn Square Wave',
      'Syn Saw Wave',
      'Syn Calliope',
      'Syn Chiff',
      'Syn Charang',
      'Syn Voice',
      'Syn Fifths Saw',
      'Syn Brass and Lead',
      'Fantasia',
      'Warm Pad',
      'Polysynth',
      'Space Vox',
      'Bowed Glass',
      'Metal Pad',
      'Halo Pad',
      'Sweep Pad',
      'Ice Rain',
      'Soundtrack',
      'Crystal',
      'Atmosphere',
      'Brightness',
      'Goblins',
      'Echo Drops',
      'Sci Fi',
      'Sitar',
      'Banjo',
      'Shamisen',
      'Koto',
      'Kalimba',
      'Bag Pipe',
      'Fiddle',
      'Shanai',
      'Tinkle Bell',
      'Agogo',
      'Steel Drums',
      'Woodblock',
      'Taiko Drum',
      'Melodic Tom',
      'Syn Drum',
      'Reverse Cymbal',
      'Guitar Fret Noise',
      'Breath Noise',
      'Seashore',
      'Bird',
      'Telephone',
      'Helicopter',
      'Applause',
      'Gunshot'
    );
  }

  /** returns list of drumset instrument names */
  public static function getDrumset() {
    return array(
      35 => 'Acoustic Bass Drum',
      36 => 'Bass Drum 1',
      37 => 'Side Stick',
      38 => 'Acoustic Snare',
      39 => 'Hand Clap',
      40 => 'Electric Snare',
      41 => 'Low Floor Tom',
      42 => 'Closed Hi-Hat',
      43 => 'High Floor Tom',
      44 => 'Pedal Hi-Hat',
      45 => 'Low Tom',
      46 => 'Open Hi-Hat',
      47 => 'Low Mid Tom',
      48 => 'High Mid Tom',
      49 => 'Crash Cymbal 1',
      50 => 'High Tom',
      51 => 'Ride Cymbal 1',
      52 => 'Chinese Cymbal',
      53 => 'Ride Bell',
      54 => 'Tambourine',
      55 => 'Splash Cymbal',
      56 => 'Cowbell',
      57 => 'Crash Cymbal 2',
      58 => 'Vibraslap',
      59 => 'Ride Cymbal 2',
      60 => 'High Bongo',
      61 => 'Low Bongo',
      62 => 'Mute High Conga',
      63 => 'Open High Conga',
      64 => 'Low Conga',
      65 => 'High Timbale',
      66 => 'Low Timbale',
      //35..66
      67 => 'High Agogo',
      68 => 'Low Agogo',
      69 => 'Cabase',
      70 => 'Maracas',
      71 => 'Short Whistle',
      72 => 'Long Whistle',
      73 => 'Short Guiro',
      74 => 'Long Guiro',
      75 => 'Claves',
      76 => 'High Wood Block',
      77 => 'Low Wood Block',
      78 => 'Mute Cuica',
      79 => 'Open Cuica',
      80 => 'Mute Triangle',
      81 => 'Open Triangle'
    );
  }

  /** returns list of standard drum kit names */
  public function getDrumkitList() {
    return array(
      1 => 'Dry',
      9 => 'Room',
      19 => 'Power',
      25 => 'Electronic',
      33 => 'Jazz',
      41 => 'Brush',
      57 => 'SFX',
      128 => 'Default'
    );
  }

  /** returns list of note names */
  public static function getNoteList() {
    //note 69 (A6) = A440
    //note 60 (C6) = Middle C
    return array(
      //Do          Re           Mi    Fa           So           La           Ti
      'C0',
      'Cs0',
      'D0',
      'Ds0',
      'E0',
      'F0',
      'Fs0',
      'G0',
      'Gs0',
      'A0',
      'As0',
      'B0',
      'C1',
      'Cs1',
      'D1',
      'Ds1',
      'E1',
      'F1',
      'Fs1',
      'G1',
      'Gs1',
      'A1',
      'As1',
      'B1',
      'C2',
      'Cs2',
      'D2',
      'Ds2',
      'E2',
      'F2',
      'Fs2',
      'G2',
      'Gs2',
      'A2',
      'As2',
      'B2',
      'C3',
      'Cs3',
      'D3',
      'Ds3',
      'E3',
      'F3',
      'Fs3',
      'G3',
      'Gs3',
      'A3',
      'As3',
      'B3',
      'C4',
      'Cs4',
      'D4',
      'Ds4',
      'E4',
      'F4',
      'Fs4',
      'G4',
      'Gs4',
      'A4',
      'As4',
      'B4',
      'C5',
      'Cs5',
      'D5',
      'Ds5',
      'E5',
      'F5',
      'Fs5',
      'G5',
      'Gs5',
      'A5',
      'As5',
      'B5',
      'C6',
      'Cs6',
      'D6',
      'Ds6',
      'E6',
      'F6',
      'Fs6',
      'G6',
      'Gs6',
      'A6',
      'As6',
      'B6',
      'C7',
      'Cs7',
      'D7',
      'Ds7',
      'E7',
      'F7',
      'Fs7',
      'G7',
      'Gs7',
      'A7',
      'As7',
      'B7',
      'C8',
      'Cs8',
      'D8',
      'Ds8',
      'E8',
      'F8',
      'Fs8',
      'G8',
      'Gs8',
      'A8',
      'As8',
      'B8',
      'C9',
      'Cs9',
      'D9',
      'Ds9',
      'E9',
      'F9',
      'Fs9',
      'G9',
      'Gs9',
      'A9',
      'As9',
      'B9',
      'C10',
      'Cs10',
      'D10',
      'Ds10',
      'E10',
      'F10',
      'Fs10',
      'G10'
    );
  }

}
